[en]
title = "My blog"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[fr]
title = "Mon blog"
description = "Mon petit blog personel"
contentDir = "content/french" 
weight = 2
#LanguageDirection = "rtl" 
LanguageName = "FR"
