  [[main]]
  name = "Accueil"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Postes"
  weight = 200
  identifier = "posts"
  url = "/fr/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/fr/portfolio/"

  [[main]]
  name = "A propos de nous"
  weight = 400
  identifier = "about"
  url = "/fr/about/"

  [[main]]
  name = "Contacte"
  weight = 500
  identifier = "contact"
  url = "/fr/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"